/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Style = IDL.Variant({
  'realistic' : IDL.Null,
  'cinematic' : IDL.Null,
  'animated' : IDL.Null,
  'abstract' : IDL.Null,
  'cartoon' : IDL.Null,
});
export const Duration = IDL.Variant({
  'long' : IDL.Null,
  'short' : IDL.Null,
  'medium' : IDL.Null,
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const VideoJob = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'duration' : Duration,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'errorMessage' : IDL.Opt(IDL.Text),
  'updatedAt' : Time,
  'style' : Style,
  'prompt' : IDL.Text,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PublicStats = IDL.Record({
  'totalCompleted' : IDL.Nat,
  'totalJobsCreated' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createVideoJob' : IDL.Func([IDL.Text, Style, Duration], [IDL.Nat], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'getAllJobs' : IDL.Func([], [IDL.Vec(VideoJob)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobsByStatus' : IDL.Func([Status], [IDL.Vec(VideoJob)], ['query']),
  'getJobsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(VideoJob)], ['query']),
  'getLatestJobs' : IDL.Func([IDL.Nat], [IDL.Vec(VideoJob)], ['query']),
  'getMyJobs' : IDL.Func([], [IDL.Vec(VideoJob)], ['query']),
  'getPublicStats' : IDL.Func([], [PublicStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoJob' : IDL.Func([IDL.Nat], [VideoJob], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'simulateProgress' : IDL.Func([], [], []),
  'updateJobMetadata' : IDL.Func([IDL.Nat, IDL.Text, Style, Duration], [], []),
  'updateJobStatus' : IDL.Func(
      [
        IDL.Nat,
        Status,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Style = IDL.Variant({
    'realistic' : IDL.Null,
    'cinematic' : IDL.Null,
    'animated' : IDL.Null,
    'abstract' : IDL.Null,
    'cartoon' : IDL.Null,
  });
  const Duration = IDL.Variant({
    'long' : IDL.Null,
    'short' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const VideoJob = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'duration' : Duration,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'errorMessage' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'style' : Style,
    'prompt' : IDL.Text,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PublicStats = IDL.Record({
    'totalCompleted' : IDL.Nat,
    'totalJobsCreated' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createVideoJob' : IDL.Func([IDL.Text, Style, Duration], [IDL.Nat], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'getAllJobs' : IDL.Func([], [IDL.Vec(VideoJob)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobsByStatus' : IDL.Func([Status], [IDL.Vec(VideoJob)], ['query']),
    'getJobsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(VideoJob)], ['query']),
    'getLatestJobs' : IDL.Func([IDL.Nat], [IDL.Vec(VideoJob)], ['query']),
    'getMyJobs' : IDL.Func([], [IDL.Vec(VideoJob)], ['query']),
    'getPublicStats' : IDL.Func([], [PublicStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoJob' : IDL.Func([IDL.Nat], [VideoJob], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'simulateProgress' : IDL.Func([], [], []),
    'updateJobMetadata' : IDL.Func(
        [IDL.Nat, IDL.Text, Style, Duration],
        [],
        [],
      ),
    'updateJobStatus' : IDL.Func(
        [
          IDL.Nat,
          Status,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };