/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Duration = { 'long' : null } |
  { 'short' : null } |
  { 'medium' : null };
export interface PublicStats {
  'totalCompleted' : bigint,
  'totalJobsCreated' : bigint,
}
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export type Style = { 'realistic' : null } |
  { 'cinematic' : null } |
  { 'animated' : null } |
  { 'abstract' : null } |
  { 'cartoon' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoJob {
  'id' : bigint,
  'status' : Status,
  'duration' : Duration,
  'thumbnailUrl' : [] | [string],
  'owner' : Principal,
  'createdAt' : Time,
  'errorMessage' : [] | [string],
  'updatedAt' : Time,
  'style' : Style,
  'prompt' : string,
  'videoUrl' : [] | [string],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createVideoJob' : ActorMethod<[string, Style, Duration], bigint>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'getAllJobs' : ActorMethod<[], Array<VideoJob>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobsByStatus' : ActorMethod<[Status], Array<VideoJob>>,
  'getJobsByUser' : ActorMethod<[Principal], Array<VideoJob>>,
  'getLatestJobs' : ActorMethod<[bigint], Array<VideoJob>>,
  'getMyJobs' : ActorMethod<[], Array<VideoJob>>,
  'getPublicStats' : ActorMethod<[], PublicStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoJob' : ActorMethod<[bigint], VideoJob>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'simulateProgress' : ActorMethod<[], undefined>,
  'updateJobMetadata' : ActorMethod<
    [bigint, string, Style, Duration],
    undefined
  >,
  'updateJobStatus' : ActorMethod<
    [bigint, Status, [] | [string], [] | [string], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];