/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface PublicStats {
    totalCompleted: bigint;
    totalJobsCreated: bigint;
}
export interface VideoJob {
    id: bigint;
    status: Status;
    duration: Duration;
    thumbnailUrl?: string;
    owner: Principal;
    createdAt: Time;
    errorMessage?: string;
    updatedAt: Time;
    style: Style;
    prompt: string;
    videoUrl?: string;
}
export interface UserProfile {
    name: string;
}
export enum Duration {
    long_ = "long",
    short_ = "short",
    medium = "medium"
}
export enum Status {
    pending = "pending",
    completed = "completed",
    processing = "processing",
    failed = "failed"
}
export enum Style {
    realistic = "realistic",
    cinematic = "cinematic",
    animated = "animated",
    abstract_ = "abstract",
    cartoon = "cartoon"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createVideoJob(prompt: string, style: Style, duration: Duration): Promise<bigint>;
    deleteJob(id: bigint): Promise<void>;
    getAllJobs(): Promise<Array<VideoJob>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getJobsByStatus(status: Status): Promise<Array<VideoJob>>;
    getJobsByUser(user: Principal): Promise<Array<VideoJob>>;
    getLatestJobs(limit: bigint): Promise<Array<VideoJob>>;
    getMyJobs(): Promise<Array<VideoJob>>;
    getPublicStats(): Promise<PublicStats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideoJob(id: bigint): Promise<VideoJob>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    simulateProgress(): Promise<void>;
    updateJobMetadata(id: bigint, prompt: string, style: Style, duration: Duration): Promise<void>;
    updateJobStatus(id: bigint, status: Status, videoUrl: string | null, thumbnailUrl: string | null, errorMessage: string | null): Promise<void>;
}
import type { Duration as _Duration, Status as _Status, Style as _Style, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VideoJob as _VideoJob } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createVideoJob(arg0: string, arg1: Style, arg2: Duration): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVideoJob(arg0, to_candid_Style_n3(this._uploadFile, this._downloadFile, arg1), to_candid_Duration_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVideoJob(arg0, to_candid_Style_n3(this._uploadFile, this._downloadFile, arg1), to_candid_Duration_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async getAllJobs(): Promise<Array<VideoJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByStatus(arg0: Status): Promise<Array<VideoJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByStatus(to_candid_Status_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByStatus(to_candid_Status_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByUser(arg0: Principal): Promise<Array<VideoJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByUser(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByUser(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestJobs(arg0: bigint): Promise<Array<VideoJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestJobs(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestJobs(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyJobs(): Promise<Array<VideoJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyJobs();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyJobs();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicStats(): Promise<PublicStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoJob(arg0: bigint): Promise<VideoJob> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoJob(arg0);
                return from_candid_VideoJob_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoJob(arg0);
            return from_candid_VideoJob_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async simulateProgress(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.simulateProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.simulateProgress();
            return result;
        }
    }
    async updateJobMetadata(arg0: bigint, arg1: string, arg2: Style, arg3: Duration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobMetadata(arg0, arg1, to_candid_Style_n3(this._uploadFile, this._downloadFile, arg2), to_candid_Duration_n5(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobMetadata(arg0, arg1, to_candid_Style_n3(this._uploadFile, this._downloadFile, arg2), to_candid_Duration_n5(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateJobStatus(arg0: bigint, arg1: Status, arg2: string | null, arg3: string | null, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobStatus(arg0, to_candid_Status_n20(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobStatus(arg0, to_candid_Status_n20(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_Duration_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Duration): Duration {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Style_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Style): Style {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_VideoJob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoJob): VideoJob {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    duration: _Duration;
    thumbnailUrl: [] | [string];
    owner: Principal;
    createdAt: _Time;
    errorMessage: [] | [string];
    updatedAt: _Time;
    style: _Style;
    prompt: string;
    videoUrl: [] | [string];
}): {
    id: bigint;
    status: Status;
    duration: Duration;
    thumbnailUrl?: string;
    owner: Principal;
    createdAt: Time;
    errorMessage?: string;
    updatedAt: Time;
    style: Style;
    prompt: string;
    videoUrl?: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n10(_uploadFile, _downloadFile, value.status),
        duration: from_candid_Duration_n12(_uploadFile, _downloadFile, value.duration),
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.thumbnailUrl)),
        owner: value.owner,
        createdAt: value.createdAt,
        errorMessage: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.errorMessage)),
        updatedAt: value.updatedAt,
        style: from_candid_Style_n15(_uploadFile, _downloadFile, value.style),
        prompt: value.prompt,
        videoUrl: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.videoUrl))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    processing: null;
} | {
    failed: null;
}): Status {
    return "pending" in value ? Status.pending : "completed" in value ? Status.completed : "processing" in value ? Status.processing : "failed" in value ? Status.failed : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    long: null;
} | {
    short: null;
} | {
    medium: null;
}): Duration {
    return "long" in value ? Duration.long : "short" in value ? Duration.short : "medium" in value ? Duration.medium : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    realistic: null;
} | {
    cinematic: null;
} | {
    animated: null;
} | {
    abstract: null;
} | {
    cartoon: null;
}): Style {
    return "realistic" in value ? Style.realistic : "cinematic" in value ? Style.cinematic : "animated" in value ? Style.animated : "abstract" in value ? Style.abstract : "cartoon" in value ? Style.cartoon : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoJob>): Array<VideoJob> {
    return value.map((x)=>from_candid_VideoJob_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Duration_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Duration): _Duration {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Style_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Style): _Style {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    pending: null;
} | {
    completed: null;
} | {
    processing: null;
} | {
    failed: null;
} {
    return value == Status.pending ? {
        pending: null
    } : value == Status.completed ? {
        completed: null
    } : value == Status.processing ? {
        processing: null
    } : value == Status.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Style): {
    realistic: null;
} | {
    cinematic: null;
} | {
    animated: null;
} | {
    abstract: null;
} | {
    cartoon: null;
} {
    return value == Style.realistic ? {
        realistic: null
    } : value == Style.cinematic ? {
        cinematic: null
    } : value == Style.animated ? {
        animated: null
    } : value == Style.abstract ? {
        abstract_: null
    } : value == Style.cartoon ? {
        cartoon: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Duration): {
    long: null;
} | {
    short: null;
} | {
    medium: null;
} {
    return value == Duration.long ? {
        long_: null
    } : value == Duration.short ? {
        short_: null
    } : value == Duration.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
